import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#fff',
  },
  heroImage: {
    width: '100%',
    height:550,
    justifyContent: 'flex-start',
  },
  logoOverlay: {
    alignItems: 'center',
    paddingTop: 90,
    paddingBottom: 12,
    paddingHorizontal: 24,
  },
  brandName: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1e6b0e',
    letterSpacing: -0.5,
    marginTop: 4,
  },
  brandSub: {
    fontSize: 13,
    color: '#555',
    textAlign: 'center',
    marginTop: 2,
    lineHeight: 18,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 50,
    backgroundColor: '#fff',
  },
  tagline: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#d0d0d0',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
    marginBottom: 14,
    height: 52,
  },
  flagPrefix: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    height: '100%',
    borderRightWidth: 1.5,
    borderRightColor: '#e0e0e0',
    backgroundColor: '#fafafa',
  },
  flagEmoji: {
    fontSize: 20,
  },
  prefixText: {
    fontSize: 14,
    color: '#444',
    fontWeight: '600',
  },
  phoneInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 15,
    color: '#222',
  },
  button: {
    backgroundColor: '#2e7d32',
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    marginBottom: 14,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  footer: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    lineHeight: 18,
  },
});